### ISSUE TITLE
memory leak on server-side rendering

### ISSUE THREAD

**Issue by lsongdev** [nofluxjs/noflux-react#15]
I use `@noflux/react@^0.5.2` with server-side rendering in my project, and it may have memory leak when i use `@connect` decorator .

node versions: 
```js
{ http_parser: '2.7.0',
  node: '8.4.0',
  v8: '6.0.286.52',
  uv: '1.13.1',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  nghttp2: '1.22.0',
  openssl: '1.0.2l',
  icu: '59.1',
  unicode: '9.0',
  cldr: '31.0.1',
  tz: '2017b' }
```

component here:
```js
import React       from 'react';
import { connect, state } from '@noflux/react';

@connect
class MyComponent extends React.Component {
  render() {
    return <div>hello { state.get('name') }</div>;
  }
}

export default MyComponent;
```

server-side rendering:
```js
import { state } from '@noflux/react';
import App       from './app';

const server = http.createServer((req, res) => {
  state.set({ name: 'noflux' });
  res.end( ReactDOM.renderToString(<App />) );
}).listen(3000);
```

I use apache http benchmarking tools for this case:
```bash
~$ ab -c100 -n50000 http://127.0.0.1:3000/
```

memory usage: 

![screen shot 2017-09-06 at 1 48 31 pm](https://user-images.githubusercontent.com/1323768/30096278-208fac7c-930a-11e7-835b-33eabaf0722c.png)

full test case here: https://github.com/song940/noflux-memory-leak

**Comment by malash** [comment]
Fixed in `@noflux/react@0.6.0`

![image](https://user-images.githubusercontent.com/1812118/30114311-1c417cb8-92dd-11e7-803d-7d4b8e19a8b9.png)
