### ISSUE TITLE
About State(dataton)

### ISSUE THREAD

**Issue by malash** [nofluxjs/noflux-react#4]
`dataton`是`noflux`中最重要的依赖包，是重构`nofux@next`绕不开的话题，因此单独开issue讨论。

# 不可变与写时复制

对于`React`等响应式框架，render = state => view是其基本原理。`state`的不可变性可以带来许多好处，如历史回放、同构渲染、便于调试等。

其中比较吸引人的是同构渲染。如果`state`可以被序列化（这通常意味着不含函数），那么后端可以将渲染的HTML与当时的`state`传递给前端，保证页面在前端正常的复现，从而实现同构渲染。

然而不可变意味着每次`state`的改变都会返回一个新的实例，action = oldState => newState，对于复杂的网站`state`可能结构很复杂，每次进行深拷贝将耗费大量的计算资源。因此写时复制（copy-on-write）作为性能优化的方法常常被采用。

具体原理不再赘述。在`dataton`中同样实现了写时复制。

# 与Immutable.js

`Immutable.js`与`dataton`类似，但对比下可以发现其设计思路的不同。

1. `Immutable.js`通过接口和类型（Map、List）的限制，保证数据一定是不可变的；`dataton`则是提供了较为基础的`get`和`set`方法，“可以”实现不可变性，这种能力是建立在使用者规范的使用前提下的。如果让一个连`Object.assign`都不知道的新手去使用`noflux`，是有可能出大问题的。（当然，`Redux`等也不能避免这种情况）

2. `Immutable.js`保持了函数式编程的传统，所有的函数都是纯函数，因此必须要处理返回值（才能把它重新存到`state`中）；而`dataton`只需要`set`即可。

我认为这里涉及一点哲学上的考虑，`dataton`的`set`确实是有副作用的函数，是因为`state`本身就像现实世界中的存储介质（内存、磁盘等），写操作就应该是有副作用的，而不可变性相只是当于磁盘快照；而在`Redux`、`Cycle.js`等较为“函数式”的框架中，`state`是一种`Functor`，对于`Functor`的操作是纯函数并没有什么问题。（所以这个问题并没有必要上升到哲学高度，好用就足够了）

3. `Immutable.js`与`Redux`等框架的合作并不“愉悦”，因为其本身是一个独立的存在；而`dataton`大部分情况下与`noflux`配合的较好，同样耦合的就更严重。

4. 待`dataton`作者 @ssnau 补充。。。

# 下一步

`noflux@next`的开发目前看起来是要对`dataton`进行一定的改动，`dataton`的定位是`noflux`的附属，还是独立的类`Immutable.js`包，值得商榷。

**Comment by malash** [comment]
对于`.cursor`与`state`同构的想法：

```javascript
state.load({
  valueA: 'abc',
  objB: {
    fieldA: 1,
    fieldB: 2
  },
  arrC: [{
    data: 1
  }, {
    data: 2
  }]
});

state instanceof Cursor === true
state.cursor('valueA') instanceof Cursor === true

state.cursor() === state

state.get('valueA') === state.cursor('valueA').get() === 'abc'

state.cursor('objB').cursor('fieldA') !== state.cursor('objB.fieldA')
state.cursor('objB').cursor('fieldA').get() === state.cursor('objB.fieldA').get()

state.cursor('arrC').get().length === 2
state.cursor('arrC').push({ data: 3});
// equals to 
// state.set('arrC', state.get('arrC').concat({ data: 3}))
state.cursor('arrC').get().length === 3
state.cursor('arrC').get(2).data === 3
```

**Comment by ssnau** [comment]
@malash  你可以为`noflux@next`单独实现一个内置的dataton而无需依赖外置包。这样的好处是：

- 无需上游改动，你可以快速试错和发布。
- 可以在此实现`cursor`与`state`的同构。

**Comment by malash** [comment]
New Noflux released.
